global:
  scrape_interval: 15s
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

storage:
  tsdb:
    out_of_order_time_window: 30m

scrape_configs:
  - job_name: aggregated-trace-metrics
    static_configs:
      - targets: ['otel-collector:8889']
    metric_relabel_configs:
      # Remove instance label
      - target_label: instance
        replacement: 'symfony2'
      - target_label: exported_instance
        replacement: 'symfony2'

  - job_name: 'jaeger'
    static_configs:
      - targets: ['otel-jaeger:14269']

#
#  - job_name: aggregated-trace-metrics
#    static_configs:
#      - targets: ['otel-jaeger:8889']
