# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

otel-logs-pipeline:
  workers: 5
  delay: 10
  source:
    otel_logs_source:
      ssl: false
  buffer:
    bounded_blocking:
  sink:
    - opensearch:
        hosts: [ "http://opensearch-node1:9200" ]
        username: "admin"
        password: "fOObar12312312!!3"
        insecure: true
        index_type: custom
        index: ss4o_logs-%{yyyy.MM.dd}
        bulk_size: 4

entry-pipeline:
  delay: "100"
  source:
    otel_trace_source:
      ssl: false
      port: 21890
  sink:
    - pipeline:
        name: "raw-pipeline"
    - pipeline:
        name: "service-map-pipeline"
raw-pipeline:
  source:
    pipeline:
      name: "entry-pipeline"
  processor:
    - otel_trace_raw:
  sink:
    - opensearch:
        hosts: [ "http://opensearch-node1:9200" ]
        username: "admin"
        password: "fOObar12312312!!3"
        insecure: true
        index_type: trace-analytics-raw
service-map-pipeline:
  delay: "100"
  source:
    pipeline:
      name: "entry-pipeline"
  processor:
    - service_map_stateful:
  sink:
    - opensearch:
        hosts: [ "http://opensearch-node1:9200" ]
        username: "admin"
        password: "fOObar12312312!!3"
        insecure: true
        index_type: trace-analytics-service-map

metrics-pipeline:
  source:
    otel_metrics_source:
      port: 21891
      ssl: false
  #      health_check_port: 21891
  sink:
    - opensearch:
        hosts: [ "http://opensearch-node1:9200" ]
        insecure: true
        index: metrics-%{yyyy.MM.dd}
        template_file: "/usr/share/data-prepper/templates/ss4o_metrics.json"


otel-metrics-pipeline:
  workers: 8
  delay: 3000
  source:
    otel_metrics_source:
      port: 21893
      health_check_service: true
      ssl: false
  buffer:
    bounded_blocking:
      buffer_size: 1024 # max number of records the buffer accepts
      batch_size: 1024 # max number of records the buffer drains after each read
  processor:
    - otel_metrics:
        calculate_histogram_buckets: true
        calculate_exponential_histogram_buckets: true
        exponential_histogram_max_allowed_scale: 10
        flatten_attributes: false
  sink:
    - opensearch:
        hosts: [ "http://opensearch-node1:9200" ]
        username: "admin"
        password: "fOObar12312312!!3"
        insecure: true
        index_type: custom
        index: ss4o_metrics-otel-%{yyyy.MM.dd}
        bulk_size: 4
        template_type: index-template
        template_file: "/usr/share/data-prepper/templates/ss4o_metrics.json"
